### PR TITLE
feat: add per service configuration for meta pool min and max connections configuration

### LINKED ISSUE #81: Make META Connection pool configuration service-specific
Currently, ZO_META_CONNECTION_POOL_MIN_SIZE and ZO_META_CONNECTION_POOL_MAX_SIZE configuration are a global ones, which means that the same value would be used by all Openobserve components.

Sometimes this is not convenient and having per service control over these env variables.

### PR DESCRIPTION
**Pull request by TessaIO**
Closes #81

### CODE REVIEW

**Comment by TessaIO** [comment]
@hengfeiyang PTAL when you have time for it

**Comment by TessaIO** [comment]
kind reminder @prabhatsharma

**Comment by hengfeiyang** [comment]
Yep, i talked with @prabhatsharma i am thinking maybe we need separate config for each service, not only connection pool, it should support all the configMap. What do you think?

**Comment by TessaIO** [comment]
@hengfeiyang can you give me a list of configs for each service so I can put it in the same PR?

**Review by prabhatsharma — APPROVED** [review]

**Pull request merged**
